from app.checks import (
    cloudtrail_event_root_activity,
    cloudtrail_event_trail_tampering,
    cloudtrail_event_iam_user_policy_attachment,
    cloudtrail_event_s3_bucket_policy_change,
    cloudtrail_event_iam_role_policy_mutation,
    cloudtrail_event_security_group_open_to_world,
    cloudtrail_event_kms_key_disabled_or_deleted,
    cloudtrail_event_guardduty_disabled,
    cloudtrail_event_config_recorder_stopped,
    cloudtrail_event_iam_access_key_created,
    cloudtrail_event_s3_public_access_block_disabled,
    cloudtrail_event_lambda_function_created_or_modified,
    cloudtrail_event_ec2_instance_tampering,
    cloudtrail_event_rds_instance_created_or_modified,
    cloudtrail_event_anomalous_api_volume,
    github_org_mfa,
    github_org_dormant,
    github_org_outside_collaborators,
    github_org_admin_unreviewed,
    github_repo_no_protection,
    github_repo_no_env_protection,
    github_repo_self_merge,
    github_repo_insufficient_reviews,
    github_repo_dependabot_disabled,
    github_repo_code_scanning_disabled,
    github_repo_secret_scanning_disabled,
    github_repo_security_status_checks,
    gitlab_org_mfa,
    gitlab_org_dormant,
    gitlab_repo_no_protection,
    gitlab_repo_self_merge,
    gitlab_repo_insufficient_reviews,
    gitlab_repo_no_env_protection,
    gitlab_repo_sast_disabled,
    gitlab_repo_dependency_scanning_disabled,
    gitlab_repo_container_scanning_disabled,
    gitlab_repo_security_ci_required,
    google_workspace_org_mfa,
    google_workspace_user_inactive,
    google_workspace_admin_unreviewed,
    entra_org_mfa,
    entra_user_inactive,
    entra_admin_unreviewed,
    okta_org_mfa,
    okta_user_inactive,
    okta_admin_unreviewed,
    okta_app_overprivileged,
    okta_api_token_stale,
    intune_device_not_encrypted,
    jamf_device_not_encrypted,
    identity_center_user_inactive,
    backup_plan_missing,
    access_analyzer_not_enabled,
    aws_account_contact_incomplete,
    aws_account_security_contact_missing,
    iam_server_certificate_expired,
    iam_cloudshell_access,
    access_key_multiple_active,
    access_key_no_rotation,
    cloudtrail_no_kms,
    cloudtrail_not_enabled,
    cloudtrail_no_log_validation,
    config_not_enabled,
    aws_config_rules_non_compliant,
    ec2_ebs_encryption_default,
    ec2_ebs_volume_unencrypted,
    ec2_imdsv2_not_required,
    ec2_instance_no_instance_profile,
    guardduty_not_enabled,
    guardduty_open_findings,
    iam_access_inventory_gap,
    iam_role_external_trust,
    iam_access_key_unused_45d,
    iam_password_policy_weak,
    iam_support_role,
    iam_perm_granted_vs_used,
    iam_root_access_keys,
    iam_root_no_mfa,
    iam_root_usage,
    iam_user_credentials_unused_45d,
    iam_user_no_mfa,
    iam_user_direct_policy,
    iam_user_admin_policy,
    kms_no_rotation,
    kms_key_policy_wildcard,
    rds_no_encryption,
    rds_no_automated_backup,
    rds_publicly_accessible,
    rds_snapshot_public,
    role_trust_wildcard,
    role_unassumed_90d,
    role_unused_services,
    iam_role_least_privilege,
    iam_policy_wildcard_resource,
    iam_policy_unattached,
    s3_account_public_access,
    s3_no_https_policy,
    s3_no_kms,
    s3_no_logging,
    s3_public_access,
    sg_default_allows_traffic,
    sg_unrestricted_rdp,
    sg_unrestricted_ssh,
    securityhub_not_enabled,
    vpc_no_flow_logs,
    s3_no_default_encryption,
    s3_no_mfa_delete,
    ebs_snapshot_public,
    ebs_snapshot_unencrypted,
    ec2_ami_public,
    ec2_ami_aged,
    cloudtrail_s3_bucket_public,
    cloudtrail_no_cloudwatch,
    cloudtrail_s3_no_logging,
    acm_cert_expiring,
    lambda_deprecated_runtime,
    lambda_no_dlq,
    rds_no_deletion_protection,
    rds_no_multi_az,
    secrets_no_rotation,
    ssm_plaintext_secret,
    elb_no_access_logs,
    elb_weak_tls,
    dynamodb_no_pitr,
    dynamodb_no_encryption,
    ecr_image_scan_disabled,
    ecr_enhanced_scanning,
    eks_public_endpoint,
    eks_control_plane_logging,
    eks_secrets_encryption,
    ecs_container_insights_disabled,
    ecs_service_public_ip,
    ecs_task_definition_privileged,
    vulnerability_monitoring_not_detected,
    inspector_active_critical,
    sns_no_encryption,
    sqs_no_encryption,
    lambda_public_function_url,
    gcp_logging_not_enabled,
    gcp_compute_instance_public_ip,
    gcp_firewall_open_ingress,
    gcp_osconfig_vuln_report_present,
    gcp_scc_not_enabled,
    gcp_asset_public_iam_binding,
    gcp_asset_public_invoker,
    azure_defender_not_enabled,
    azure_storage_public_blob_access,
    azure_compute_instance_public_ip,
    azure_logging_not_enabled,
    azure_entra_privileged_role_assignment,
    azure_policy_non_compliant,
)

ALL_CHECKS = [
    # root (critical — run first)
    iam_root_access_keys,
    iam_root_no_mfa,
    iam_root_usage,
    # IAM account
    iam_password_policy_weak,
    iam_support_role,
    # IAM users
    iam_user_credentials_unused_45d,
    iam_access_key_unused_45d,
    access_key_no_rotation,
    access_key_multiple_active,
    iam_user_no_mfa,
    iam_user_direct_policy,
    iam_user_admin_policy,
    # IAM roles / policies
    role_unassumed_90d,
    iam_role_least_privilege,
    iam_perm_granted_vs_used,
    iam_policy_wildcard_resource,
    iam_policy_unattached,
    iam_role_external_trust,
    iam_access_inventory_gap,
    role_unused_services,
    role_trust_wildcard,
    # S3
    s3_account_public_access,
    s3_public_access,
    s3_no_https_policy,
    s3_no_kms,
    s3_no_logging,
    # KMS
    kms_no_rotation,
    kms_key_policy_wildcard,
    # CloudTrail
    cloudtrail_not_enabled,
    cloudtrail_no_log_validation,
    cloudtrail_no_kms,
    # CloudTrail event-based checks
    cloudtrail_event_root_activity,
    cloudtrail_event_trail_tampering,
    cloudtrail_event_iam_user_policy_attachment,
    cloudtrail_event_s3_bucket_policy_change,
    cloudtrail_event_iam_role_policy_mutation,
    cloudtrail_event_security_group_open_to_world,
    cloudtrail_event_kms_key_disabled_or_deleted,
    cloudtrail_event_guardduty_disabled,
    cloudtrail_event_config_recorder_stopped,
    cloudtrail_event_iam_access_key_created,
    cloudtrail_event_s3_public_access_block_disabled,
    cloudtrail_event_lambda_function_created_or_modified,
    cloudtrail_event_ec2_instance_tampering,
    cloudtrail_event_rds_instance_created_or_modified,
    cloudtrail_event_anomalous_api_volume,
    # GuardDuty
    guardduty_not_enabled,
    guardduty_open_findings,
    # Access Analyzer
    access_analyzer_not_enabled,
    aws_account_contact_incomplete,
    aws_account_security_contact_missing,
    iam_server_certificate_expired,
    iam_cloudshell_access,
    backup_plan_missing,
    # AWS Config
    config_not_enabled,
    aws_config_rules_non_compliant,
    # Security Hub
    securityhub_not_enabled,
    # VPC
    vpc_no_flow_logs,
    # EC2 Security Groups
    sg_unrestricted_ssh,
    sg_unrestricted_rdp,
    sg_default_allows_traffic,
    # EC2 Instances
    ec2_imdsv2_not_required,
    ec2_instance_no_instance_profile,
    ec2_ebs_encryption_default,
    ec2_ebs_volume_unencrypted,
    # RDS
    rds_publicly_accessible,
    rds_no_encryption,
    rds_no_automated_backup,
    rds_snapshot_public,
    # GitHub identity
    github_org_mfa,
    github_org_dormant,
    github_org_outside_collaborators,
    github_org_admin_unreviewed,
    github_repo_no_protection,
    github_repo_no_env_protection,
    github_repo_self_merge,
    github_repo_insufficient_reviews,
    github_repo_dependabot_disabled,
    github_repo_code_scanning_disabled,
    github_repo_secret_scanning_disabled,
    github_repo_security_status_checks,
    # GitLab identity
    gitlab_org_mfa,
    gitlab_org_dormant,
    gitlab_repo_no_protection,
    gitlab_repo_self_merge,
    gitlab_repo_insufficient_reviews,
    gitlab_repo_no_env_protection,
    gitlab_repo_sast_disabled,
    gitlab_repo_dependency_scanning_disabled,
    gitlab_repo_container_scanning_disabled,
    gitlab_repo_security_ci_required,
    # Google Workspace / Entra identity
    google_workspace_org_mfa,
    google_workspace_user_inactive,
    google_workspace_admin_unreviewed,
    entra_org_mfa,
    entra_user_inactive,
    entra_admin_unreviewed,
    okta_org_mfa,
    okta_user_inactive,
    okta_admin_unreviewed,
    okta_app_overprivileged,
    okta_api_token_stale,
    intune_device_not_encrypted,
    jamf_device_not_encrypted,
    identity_center_user_inactive,
    # AWS gap checks (session 18)
    s3_no_default_encryption,
    s3_no_mfa_delete,
    ebs_snapshot_public,
    ebs_snapshot_unencrypted,
    ec2_ami_public,
    ec2_ami_aged,
    cloudtrail_s3_bucket_public,
    cloudtrail_no_cloudwatch,
    cloudtrail_s3_no_logging,
    acm_cert_expiring,
    lambda_deprecated_runtime,
    lambda_no_dlq,
    lambda_public_function_url,
    rds_no_deletion_protection,
    rds_no_multi_az,
    secrets_no_rotation,
    ssm_plaintext_secret,
    elb_no_access_logs,
    elb_weak_tls,
    dynamodb_no_pitr,
    dynamodb_no_encryption,
    ecr_image_scan_disabled,
    ecr_enhanced_scanning,
    eks_public_endpoint,
    eks_control_plane_logging,
    eks_secrets_encryption,
    ecs_container_insights_disabled,
    ecs_service_public_ip,
    ecs_task_definition_privileged,
    vulnerability_monitoring_not_detected,
    inspector_active_critical,
    sns_no_encryption,
    sqs_no_encryption,
    # GCP / Azure phase-one
    gcp_logging_not_enabled,
    gcp_compute_instance_public_ip,
    gcp_firewall_open_ingress,
    gcp_osconfig_vuln_report_present,
    gcp_scc_not_enabled,
    gcp_asset_public_iam_binding,
    gcp_asset_public_invoker,
    azure_defender_not_enabled,
    azure_storage_public_blob_access,
    azure_compute_instance_public_ip,
    azure_logging_not_enabled,
    azure_entra_privileged_role_assignment,
    azure_policy_non_compliant,
]

# Source-control checks (GitHub/GitLab) are an org-level domain driven by git
# sync, not by a cloud-account scan. They run in the sync path and persist
# findings org-scoped (account_id=NULL); the cloud scan pipeline excludes them.
SOURCE_CONTROL_PREFIXES = ("github.", "gitlab.")


def is_source_control_check(check_id: str) -> bool:
    return check_id.startswith(SOURCE_CONTROL_PREFIXES)


SOURCE_CONTROL_CHECKS = [mod for mod in ALL_CHECKS if is_source_control_check(mod.CHECK_ID)]


def source_control_checks_for(provider_type: str) -> list:
    """Check modules for one provider type ('github' or 'gitlab')."""
    prefix = f"{provider_type}."
    return [mod for mod in SOURCE_CONTROL_CHECKS if mod.CHECK_ID.startswith(prefix)]


# Identity integration checks (Okta testing, Entra, Google Workspace) are
# org-level — driven by integration sync, not cloud-account scan.
INTEGRATION_SYNC_PREFIXES = ("okta.", "entra.", "google_workspace.")


def is_integration_sync_check(check_id: str) -> bool:
    return check_id.startswith(INTEGRATION_SYNC_PREFIXES)


INTEGRATION_SYNC_CHECKS = [mod for mod in ALL_CHECKS if is_integration_sync_check(mod.CHECK_ID)]


def integration_sync_checks_for(provider_type: str) -> list:
    """Check modules for one provider type ('okta'|'entra'|'google_workspace')."""
    prefix = f"{provider_type}."
    return [mod for mod in INTEGRATION_SYNC_CHECKS if mod.CHECK_ID.startswith(prefix)]
